FROM althack/ros2:humble-base

# SHELL ["/bin/bash", "-c"]


ENV DEBIAN_FRONTEND=noninteractive

ENV BUILD_LOCATION=./build
ENV INSTALL_LOCATION=./install
ENV ROS_DISTRO=humble

# Install dependencies

COPY ./dependencies /dep

COPY ./commands /cmd

RUN --mount=type=cache,target=/var/cache/apt apt update -y

RUN --mount=type=cache,target=/var/cache/apt apt install gettext -y

RUN export ROS_DISTRO=${ROS_DISTRO} && (cat '/dep/packages.txt' | envsubst) > '/dep/packages1.txt'

RUN apt update

RUN apt install git ninja-build meson udev python3-ply python3-jinja2 libglib2.0-dev \
libgstreamer-plugins-base1.0-dev libboost-dev libgnutls28-dev openssl libtiff-dev pybind11-dev libusb-1.0-0-dev  -y

RUN --mount=type=cache,target=/var/cache/apt  cat '/dep/packages1.txt' | xargs apt -y install

RUN apt install python3-colcon-common-extensions python3-rosdep python3-pip -y

# Install libfreenect

WORKDIR / 

RUN git clone https://github.com/OpenKinect/libfreenect

WORKDIR /libfreenect

RUN mkdir build

WORKDIR /libfreenect/build

RUN cmake -L ..

RUN make

RUN make install

# Install edgetpu

WORKDIR /

RUN echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | tee /etc/apt/sources.list.d/coral-edgetpu.list

RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

RUN apt update

RUN apt install devscripts debhelper dkms  -y

RUN apt install /debs/libedgetpu-dev.deb /debs/libedgetpu1-std.deb -y

RUN git clone https://github.com/google/gasket-driver.git

WORKDIR /gasket-driver

RUN debuild -us -uc -tc -b

WORKDIR /

RUN dpkg -i gasket-dkms_1.0-18_all.deb

RUN ldconfig

RUN chmod -R a+x /app/cmd

WORKDIR /

# Create workspace

RUN mkdir -p /app

RUN apt install -y tini

# Copy entrypoint

COPY ./entrypoints/entrypoint.prod.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/usr/bin/tini", "--"]

CMD [ "/entrypoint.sh" ]